In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("bpp_training_data.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296440 entries, 0 to 296439
Data columns (total 56 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   296440 non-null  int64
 1   SalePrice                 296439 non-null  float64
 2   MachineID                 296439 non-null  float64
 3   ModelID                   296439 non-null  float64
 4   datasource                296439 non-null  float64
 5   auctioneerID              296439 non-null  float64
 6   YearMade                  296439 non-null  float64
 7   MachineHoursCurrentMeter  296439 non-null  float64
 8   UsageBand                 296439 non-null  float64
 9   fiModelDesc               296439 non-null  float64
 10  fiBaseModel               296439 non-null  float64
 11  fiSecondaryDesc           296439 non-null  float64
 12  fiModelSeries             296439 non-null  float64
 13  fiModelDescriptor         296439 non-null  float64
 14  ProductSize               296439 non-null  float64
 15  fiProductClassDesc        296439 non-null  float64
 16  state                     296439 non-null  float64
 17  ProductGroup              296439 non-null  float64
 18  ProductGroupDesc          296439 non-null  float64
 19  Drive_System              296439 non-null  float64
 20  Enclosure                 296439 non-null  float64
 21  Forks                     296439 non-null  float64
 22  Pad_Type                  296439 non-null  float64
 23  Ride_Control              296439 non-null  float64
 24  Stick                     296439 non-null  float64
 25  Transmission              296439 non-null  float64
 26  Turbocharged              296439 non-null  float64
 27  Blade_Extension           296439 non-null  float64
 28  Blade_Width               296439 non-null  float64
 29  Enclosure_Type            296439 non-null  float64
 30  Engine_Horsepower         296439 non-null  float64
 31  Hydraulics                296439 non-null  float64
 32  Pushblock                 296439 non-null  float64
 33  Ripper                    296439 non-null  float64
 34  Scarifier                 296439 non-null  float64
 35  Tip_Control               296439 non-null  float64
 36  Tire_Size                 296439 non-null  float64
 37  Coupler                   296439 non-null  float64
 38  Coupler_System            296439 non-null  float64
 39  Grouser_Tracks            296439 non-null  float64
 40  Hydraulics_Flow           296439 non-null  float64
 41  Track_Type                296439 non-null  float64
 42  Undercarriage_Pad_Width   296439 non-null  float64
 43  Stick_Length              296439 non-null  float64
 44  Thumb                     296439 non-null  float64
 45  Pattern_Changer           296439 non-null  float64
 46  Grouser_Type              296439 non-null  float64
 47  Backhoe_Mounting          296439 non-null  float64
 48  Blade_Type                296439 non-null  float64
 49  Travel_Controls           296439 non-null  float64
 50  Differential_Type         296439 non-null  float64
 51  Steering_Controls         296439 non-null  float64
 52  saleYear                  296439 non-null  float64
 53  saleMonth                 296439 non-null  float64
 54  saleDay                   296439 non-null  float64
 55  saleDayOfYear             296439 non-null  float64
dtypes: float64(55), int64(1)
memory usage: 126.7 MB

In [5]:
df.drop(["SalesID"],axis=1,inplace=True)

In [6]:
df.drop(["MachineID"],axis=1,inplace=True)

In [7]:
df.drop(["auctioneerID"],axis=1,inplace=True)

In [8]:
df.drop(["ModelID"],axis=1,inplace=True)

In [9]:
x=df.drop(['SalePrice'],axis=1).values

y=df['SalePrice'].values

In [10]:
df.drop([296439],axis=0,inplace=True)

In [11]:
x=df.drop(['SalePrice'],axis=1).values

y=df['SalePrice'].values

In [12]:

df

,SalePrice,datasource,YearMade,MachineHoursCurrentMeter,UsageBand,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,...,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls,saleYear,saleMonth,saleDay,saleDayOfYear
0,9500.0,132.0,1974.0,17.0,0.0,4593.0,1744.0,0.0,0.0,0.0,...,0.0,1.0,8.0,6.0,0.0,0.0,1989.0,1.0,17.0,17.0
1,14000.0,132.0,1980.0,31.0,0.0,1820.0,559.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,2.0,1989.0,1.0,31.0,31.0
2,50000.0,132.0,1978.0,31.0,0.0,2348.0,713.0,59.0,0.0,0.0,...,0.0,1.0,8.0,6.0,0.0,0.0,1989.0,1.0,31.0,31.0
3,16000.0,132.0,1980.0,31.0,0.0,1819.0,558.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,2.0,1989.0,1.0,31.0,31.0
4,22000.0,132.0,1984.0,31.0,0.0,2119.0,683.0,21.0,0.0,0.0,...,0.0,1.0,6.0,5.0,0.0,0.0,1989.0,1.0,31.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296434,60000.0,136.0,2007.0,61.0,3.0,1202.0,354.0,75.0,0.0,0.0,...,0.0,1.0,6.0,6.0,0.0,0.0,2009.0,3.0,2.0,61.0
296435,10000.0,172.0,2000.0,61.0,3.0,1619.0,477.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2009.0,3.0,2.0,61.0
296436,25000.0,136.0,2003.0,61.0,0.0,1197.0,354.0,61.0,0.0,71.0,...,0.0,1.0,6.0,6.0,0.0,0.0,2009.0,3.0,2.0,61.0
296437,12000.0,172.0,2005.0,61.0,3.0,4261.0,1538.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2009.0,3.0,2.0,61.0
296438,12500.0,136.0,1971.0,61.0,0.0,22.0,11.0,57.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2009.0,3.0,2.0,61.0

In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)

In [14]:
classifier_rf.fit(x, y)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)